### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by Amber-Yerkey** [learn-co-curriculum/phase-3-quiz-class-variables-and-methods#1] opened 2022-07-23 20:20 UTC
### Canvas Link

https://my.learn.co/courses/382/quizzes/2257

### Concern

When reviewing incorrect answers on this quiz "Class Variables and Methods Quiz ", one of the source links is for the page "Class Constants." The link is broken for all instances of this and not sure what it's meant to link to.

### Additional Context

This is what the button on the review page links to: [Class Constants](https://my.learn.co/courses/382/quizzes/$CANVAS_OBJECT_REFERENCE$/assignments/gf5c86eb8b5adc54e528911d21d7c14ea)

I think this may be the intended page: https://my.learn.co/courses/382/pages/class-variables-and-class-methods?module_item_id=42105 because it reviews class constants but not sure.

**Comment by lizbur10** [comment] 2022-08-01 17:24
Hi @Amber-Yerkey - I'm not able to reproduce this issue. When I go to the quiz and click the links, they are all linked correctly to the page you identified above. Given that, I'm not sure how to fix the problem. Was it only the Class Variables and Class Methods links that were broken?

**Comment by lizbur10** [comment] 2022-08-12 12:42
I'm going to go ahead and close this issue. Thanks for reporting the problem and apologies for the inconvenience.

**Closed as completed by lizbur10** 2022-08-12 12:42 UTC
Labels: se curriculum
